# Generated by Django 2.2.18 on 2021-06-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedauser',
            name='jasminaccountid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
