# Generated by Django 2.2.18 on 2021-07-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_cedauser_jasminaccountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedauser',
            name='ftp_password',
            field=models.BooleanField(default=False, help_text='Indicates if this user has created a FTP password.'),
        ),
    ]
