# Generated by Django 3.2.20 on 2023-08-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_cedauser_ftp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedauser',
            name='has_access_token',
            field=models.BooleanField(default=False, help_text='Indicates if this user has created an Access Token.'),
        ),
    ]
