# Generated by Django 3.2.20 on 2023-08-16 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_cedauser_has_access_tokem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='An access token that allows for access to the CEDA API', verbose_name='API Access token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CEDA Access Token',
                'verbose_name_plural': 'CEDA Access Tokens',
            },
        ),
    ]
