# Generated by Django 3.2.20 on 2023-08-23 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_accesstokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstokens',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 14, 46, 29, 8946), help_text='The tokens expiry date', verbose_name='Token Expiry Date'),
            preserve_default=False,
        ),
    ]
