# Generated by Django 3.2.20 on 2023-08-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_accesstokens_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstokens',
            options={'verbose_name': ('CEDA Access Token',), 'verbose_name_plural': ('CEDA Access Tokens',)},
        ),
        migrations.AddField(
            model_name='accesstokens',
            name='token_name',
            field=models.TextField(blank=True, help_text='An optional name for the token', null=True, verbose_name='Name of token for easy reference'),
        ),
    ]
