[tool.poetry]
name = "ceda-services-portal"
version = "0.2.0"
description = "Django application for registering and managing CEDA users."
license = "BSD-3-Clause"
authors = ["William Tucker <william.tucker@stfc.ac.uk>"]
maintainers = ["William Tucker <william.tucker@stfc.ac.uk>"]
readme = "README.md"
repository = "https://github.com/cedadev/ceda-services-portal"
classifiers = [
    "Development Status :: 2 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Operating System :: POSIX :: Linux",
]

packages = [
    { include = "services_portal_site"},
    { include = 'account'},
]
include = ["templates/*"]

# poetry export -f requirements.txt -o requirements.txt --without-hashes
[tool.poetry.dependencies]
python = "^3.8"
crypto-cookie = {git = "https://github.com/cedadev/crypto-cookie.git", rev = "b92dd9e6cc910d48d9380222c9273c8929666980"}
dj-security-middleware = {git = "https://github.com/cedadev/dj-security-middleware.git", rev = "a274146198848db1684c366400d57376509b52d9"}
Django = "~3.2"
django-cookie-law = "2.1.0"
django-countries = "~7.2.1"
django-crispy-forms = "^1.14.0"
django-markdown-deux = "^1.0.5"
django-oidc-extras = {git = "https://github.com/cedadev/django-oidc-extras.git", rev = "7865641af8e0886bca244e2fc9ab27221f518ef8"}
django-polymorphic = "^3.1.0"
django-widget-tweaks = "^1.4.12"
djangorestframework = "^3.13.1"
fwtheme-django = {git = "https://github.com/cedadev/fwtheme-django.git", tag = "1.0.1"}
fwtheme-django-ceda-serv = {git = "https://github.com/cedadev/fwtheme-django-ceda-serv.git", tag = "1.5.0"}
importlib-metadata = "^4.11.0"
jasmin-django-utils = {git = "https://github.com/cedadev/jasmin-django-utils.git", tag = "v1.0.5"}
jasmin-ldap = {git = "https://github.com/cedadev/jasmin-ldap.git", tag = "v1.0.0"}
jasmin-ldap-django = {git = "https://github.com/cedadev/jasmin-ldap-django.git", tag = "v1.0.1"}
jasmin-metadata = {git = "https://github.com/cedadev/jasmin-metadata.git", tag = "v1.0.0"}
jasmin-notifications = {git = "https://github.com/cedadev/jasmin-notifications.git", tag = "v1.0.0"}
jasmin-services = {git = "https://github.com/cedadev/jasmin-services.git", tag = "v1.1.5"}
mozilla-django-oidc = "^2.0.0"
oauthlib = "^3.2.0"
pika = "^1.2.0"
psycopg2-binary = "^2.9.3"
python-dateutil = "^2.8.2"
requests-oauthlib = "^1.3.1"

[tool.poetry.dev-dependencies]
pytest-runner = "^5.3.1"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
