[tool.poetry]
name = "ceda-services-portal"
version = "0.1.0"
description = ""
authors = ["William Tucker <william.tucker@stfc.ac.uk>"]

packages = [
    { include = "services_portal_site"},
    { include = 'account'},
]

[tool.poetry.dependencies]
python = "^3.8"
crypto-cookie = {git = "https://github.com/cedadev/crypto-cookie.git", rev = "b92dd9e6cc910d48d9380222c9273c8929666980"}
dj-security-middleware = {git = "https://github.com/cedadev/dj-security-middleware.git", rev = "a274146198848db1684c366400d57376509b52d9"}
Django = "~3.2"
django-cookie-law = "^2.1.1"
django-countries = "^7.3"
django-crispy-forms = "^1.14.0"
django-markdown-deux = "^1.0.5"
django-oidc-extras = {git = "https://github.com/cedadev/django-oidc-extras.git", rev = "7865641af8e0886bca244e2fc9ab27221f518ef8"}
django-polymorphic = "^3.1.0"
django-widget-tweaks = "^1.4.12"
djangorestframework = "^3.13.1"
fwtheme-django = {git = "https://github.com/cedadev/fwtheme-django.git", rev = "38bd08d6572fe5f17ab02a3fc420a63d651b97e7"}
fwtheme-django-ceda-serv = {git = "https://github.com/cedadev/fwtheme-django-ceda-serv.git", rev = "c1ac0bd232bc5410a70d2a60fb5b4ec0098e34b6"}
importlib-metadata = "^4.11.0"
jasmin-django-utils = {git = "https://github.com/cedadev/jasmin-django-utils.git", rev = "a971fe565dabcfac0ed9a8af426aafdba1702b7c"}
jasmin-ldap = {git = "https://github.com/cedadev/jasmin-ldap.git", rev = "ad21e8f7d8d82e33e5bf48820bf5f9e630a53d8d"}
jasmin-ldap-django = {git = "https://github.com/cedadev/jasmin-ldap-django.git", rev = "0374f2f9146279d5dd9b2a19b628d7da76b663f9"}
jasmin-metadata = {git = "https://github.com/cedadev/jasmin-metadata.git", rev = "d6c8666be451eb7be0966a5c04923830145e0408"}
jasmin-notifications = {git = "https://github.com/cedadev/jasmin-notifications.git", tag = "v1.0.0"}
jasmin-services = {git = "https://github.com/cedadev/jasmin-services.git", rev = "686af634b4fc22b41032521010118c0134728d6e"}
mozilla-django-oidc = "^2.0.0"
oauthlib = "^3.2.0"
pika = "^1.2.0"
psycopg2-binary = "^2.9.3"
python-dateutil = "^2.8.2"
requests-oauthlib = "^1.3.1"

[tool.poetry.dev-dependencies]
pytest-runner = "^5.3.1"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
